# Could be better but it's whatever for now

name: Sync Files To Main Server

on:
  push:
    branches: master
  workflow_dispatch:
  
jobs:
  upload:
    name: Sync Files
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Sync BossHud Files
        uses: SnowyGFL/FTP-Deploy-Action@1.1
        with:
          server: ${{ secrets.ftp_main_server }}
          username: ${{ secrets.ftp_main_username }}
          password: ${{ secrets.ftp_main_password }}
          local-dir: bosshud/
          server-dir: csgo/addons/sourcemod/configs/MapBossHP/
          log-level: verbose

      - name: Sync entWatch Files
        uses: SnowyGFL/FTP-Deploy-Action@1.1
        with:
          server: ${{ secrets.ftp_main_server }}
          username: ${{ secrets.ftp_main_username }}
          password: ${{ secrets.ftp_main_password }}
          local-dir: entwatch/
          server-dir: csgo/cfg/sourcemod/entwatch/maps/

      - name: Sync SaveLevel Files
        uses: SnowyGFL/FTP-Deploy-Action@1.1
        with:
          server: ${{ secrets.ftp_main_server }}
          username: ${{ secrets.ftp_main_username }}
          password: ${{ secrets.ftp_main_password }}
          local-dir: savelevel/
          server-dir: csgo/addons/sourcemod/configs/savelevel/

      - name: Sync Stripper Files
        uses: SnowyGFL/FTP-Deploy-Action@1.1
        with:
          server: ${{ secrets.ftp_main_server }}
          username: ${{ secrets.ftp_main_username }}
          password: ${{ secrets.ftp_main_password }}
          local-dir: stripper/
          server-dir: csgo/addons/stripper/maps/

      - name: Sync VScript Files
        uses: SnowyGFL/FTP-Deploy-Action@1.1
        with:
          server: ${{ secrets.ftp_main_server }}
          username: ${{ secrets.ftp_main_username }}
          password: ${{ secrets.ftp_main_password }}
          local-dir: vscripts/
          server-dir: csgo/scripts/vscripts/gfl/
